# Generated by Django 5.2.8 on 2025-11-19 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Empresa/Patrocinador')),
                ('category', models.CharField(choices=[('EMP', 'Empresarial'), ('LIB', 'Libre'), ('VET', 'Veteranos')], max_length=3)),
                ('game_format', models.CharField(choices=[('7', '7 vs 7'), ('8', '8 vs 8'), ('9', '9 vs 9')], max_length=1, verbose_name='Formato')),
                ('delegate_name', models.CharField(max_length=150, verbose_name='Nombre del delegado')),
                ('delegate_phone', models.CharField(max_length=30, verbose_name='Teléfono del delegado')),
                ('delegate_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del delegado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRE_REGISTRADO', 'Pre-registrado (sin comprobante)'), ('COMPROBANTE_ENVIADO', 'Comprobante enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EXPIRADO', 'Expirado')], default='PRE_REGISTRADO', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('payment_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tournament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comprobantes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='inscripciones.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='inscripciones.tournament'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Número')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='inscripciones.team')),
            ],
            options={
                'ordering': ['team', 'jersey_number'],
                'unique_together': {('team', 'jersey_number'), ('team', 'last_name', 'first_name')},
            },
        ),
    ]
