# Generated by Django 5.2.8 on 2025-11-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='game_format',
        ),
    ]
