# Generated by Django 5.2.8 on 2025-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_remove_team_game_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alternate_delegate_ine',
            field=models.FileField(blank=True, null=True, upload_to='ines/', verbose_name='INE del suplente'),
        ),
        migrations.AddField(
            model_name='team',
            name='alternate_delegate_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del responsable suplente'),
        ),
        migrations.AddField(
            model_name='team',
            name='alternate_delegate_office_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de oficina del suplente'),
        ),
        migrations.AddField(
            model_name='team',
            name='alternate_delegate_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del suplente'),
        ),
        migrations.AddField(
            model_name='team',
            name='delegate_ine',
            field=models.FileField(blank=True, null=True, upload_to='ines/', verbose_name='INE del delegado'),
        ),
        migrations.AddField(
            model_name='team',
            name='delegate_office_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de oficina del delegado'),
        ),
        migrations.AddField(
            model_name='team',
            name='preferred_days',
            field=models.CharField(blank=True, max_length=50, verbose_name='Días preferentes de juego'),
        ),
    ]
