# Generated by Django 5.2.8 on 2025-11-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_team_alternate_delegate_ine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='inscripciones.team'),
        ),
    ]
