# Generated by Django 5.2.8 on 2025-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_alter_paymentproof_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentproof',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='player',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Meses adicionales (0–11).', null=True, verbose_name='Edad (meses)'),
        ),
        migrations.AddField(
            model_name='player',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (años)'),
        ),
        migrations.AddField(
            model_name='player',
            name='imss_number',
            field=models.CharField(blank=True, help_text='Si es refuerzo y no tiene IMSS, deja en blanco.', max_length=20, verbose_name='Número IMSS'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_reinforcement',
            field=models.BooleanField(default=False, help_text='Marca esta casilla si el jugador es refuerzo.', verbose_name='Es refuerzo'),
        ),
    ]
