# Generated by Django 5.2.8 on 2025-11-20 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_alter_paymentproof_options_player_age_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Meses adicionales (1–12).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Edad (meses)'),
        ),
    ]
