# Generated by Django 5.2.8 on 2025-11-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_alter_player_age_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores_fotos/', verbose_name='Foto del jugador (opcional)'),
        ),
    ]
