# Generated by Django 5.2.8 on 2025-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='employer_registration',
            field=models.CharField(blank=True, help_text='Registro patronal de la empresa ante el IMSS', max_length=20, verbose_name='Número patronal IMSS'),
        ),
    ]
