# Generated by Django 5.2.8 on 2025-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0008_team_employer_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='employer_registration',
        ),
        migrations.AddField(
            model_name='team',
            name='employer_number_imss',
            field=models.CharField(blank=True, help_text='Número patronal registrado ante el IMSS (opcional).', max_length=20, verbose_name='Número patronal IMSS'),
        ),
    ]
