# Generated by Django 5.2.8 on 2025-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_remove_team_employer_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curp',
            field=models.CharField(blank=True, help_text='CURP del jugador (opcional).', max_length=18, verbose_name='CURP'),
        ),
    ]
