# Generated by Django 5.2.8 on 2025-12-04 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_player_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre interno')),
                ('position', models.CharField(choices=[('TOP', 'Banner superior'), ('SIDEBAR', 'Banner lateral'), ('BOTTOM', 'Banner inferior')], max_length=10, verbose_name='Posición')),
                ('image', models.ImageField(upload_to='publicidad/', verbose_name='Imagen del banner')),
                ('link_url', models.URLField(blank=True, help_text='Opcional. Link al hacer clic en el banner.', verbose_name='URL de destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Se usa para ordenar los banners dentro de la misma posición.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Meses adicionales (0–12).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Edad (meses)'),
        ),
    ]
