# Generated by Django 5.2.8 on 2025-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0011_adbanner_alter_player_age_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='image_url',
            field=models.URLField(blank=True, help_text='Opcional. Si se especifica, se usará en lugar de la imagen subida.', verbose_name='URL de imagen externa'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicidad/', verbose_name='Imagen del banner'),
        ),
    ]
