# Generated by Django 5.2.8 on 2025-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0012_adbanner_image_url_alter_adbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='access_pin',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos para editar jugadores.', max_length=4, verbose_name='PIN de acceso'),
        ),
    ]
