# Generated by Django 5.2.8 on 2025-12-14 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0013_team_access_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Meses adicionales (1–12).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Edad (meses)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='preferred_days',
            field=models.CharField(blank=True, help_text='Códigos separados por coma, ej. "LUN,MIE".', max_length=50, verbose_name='Días preferentes de juego'),
        ),
    ]
